### ISSUE TITLE
Cannot find fragmentHideStrategy method

### ISSUE THREAD

**Issue by abdulwasae** [ncapdevi/FragNav#130]
I want to change the fragment hiding strategy for my app, but i am unable to find the following methods in the builder or anywhere. I am using version 2.4.0

`...
.fragmentHideStrategy(FragNavController.DETACH_ON_NAVIGATE_HIDE_ON_SWITCH)
.eager(true)
...`

**Comment by ncapdevi** [comment]
Unfortunately that's true.  The feature got added after 2.4.0, and work on 3.0 has begun since then, so there are 3 options.
 1. You can fork off a version of the project from after it was added and use that.
 2. I could roll back and create and push out a 2.5.0 which includes this.
3. You can wait until 3.0 to come out in the next couple weeks.


I will try to push out a 2.5.0 update in the next couple of days, and hopefully can, but if not, it'll just be a bit of the wait, sorry about that.
