### ISSUE TITLE
Empy fragment on back navigation, which leads to crash

### ISSUE THREAD

**Issue by p-fischer** [ncapdevi/FragNav#32]
I'm using FragNav together with bottmbar:
`compile 'com.roughike:bottom-bar:1.3.4'`

I updated from your former master branch state (something after version 1.0.3) to 1.2.2.

I did that by only exting the constructor call by the starting index.

```
navController = new FragNavController( savedInstanceState, getSupportFragmentManager(), R.id.container, fragments, INDEX_1 );
```

Now, when I press the back button on "base fragment" of a tab, I see an "empty fragment".

My onBackPressed implementation:
```
@Override
public void onBackPressed()
{
	if ( popFragment() )
	{
		return;
	}
	super.onBackPressed();
}

@Override
public boolean popFragment()
{
	if ( navController != null && navController.getCurrentStack() != null && !navController.getCurrentStack().empty() )
	{
		navController.pop();
		return true;
	}
	return false;
}
```

If I select another tab, and then select the "empty" tab again. I run into this crash:

> java.lang.IllegalStateException: Either you haven't past in a fragment at this index in your constructor, or you haven'tprovided a way to create it while via your RootFragmentListener.getRootFragment(index)
                                                         at com.ncapdevi.fragnav.FragNavController.getRootFragment(FragNavController.java:417)
                                                         at com.ncapdevi.fragnav.FragNavController.switchTab(FragNavController.java:204)
                                                         at com.anfema.kidswatch.activities.MainActivity$1.onMenuTabSelected(MainActivity.java:260)

I did not implement `getRootFragment` in my app because I pass the base fragments through the constructor call.

**Comment by ncapdevi** [comment]
I suggest using the 'canPop()' method instead, but essentially what is happening, is you're checking if the stack is not empty, and if it isn't you're popping off. This isn't what you want, you want to make sure that you don't pop off the bottom fragment, so you want to check to see if the size>1 and pop off (or just use the canPop() method).  The reason that you're getting that error is because you popped off the only instance that you had of the baseFragment and now it doesn't know what to do, and you haven't provided a new way to create one.

```
@Override
public void onBackPressed()
{
	if (! popFragment() )
	{
	      super.onBackPressed();
	}
}


@Override
public boolean popFragment()
{
	if ( navController != null && navController.canPop()) )
	{
		navController.pop();
		return true;
	}
	return false;
}
```
