### ISSUE TITLE
What's push fragment?

### ISSUE THREAD

**Issue by DanteAndroid** [ncapdevi/FragNav#52]
What does push mean? Does it mean `add`?
If so, I think to use the same name of official fragment API would be better.

**Comment by ncapdevi** [comment]
Yeah, I could see that, but `push` we chosen because these tabs act as stacks. Using  `add` would be ambiguous as to the underlying data structure; is it adding to above the last fragment? Below the last fragment? In between fragments 4 and 5? By using Stack terminology of `push, `pop` and `replace` it's clear (assuming you're familiar with basic data structures) what exactly is happening.
