### ISSUE TITLE
popFragment

### ISSUE THREAD

**Issue by pablojoseoroz** [ncapdevi/FragNav#64]
Hi, this library is very useful to me. But I have a question about backstack when adding fragment... I have observed that when I use pop the fragment that is going to show is recreated again. It is possible to when I do a pop, do used about popBackStack()?? 
Else, how I know if the fragment will be shown is recreated or new?
Thank a lot,
Pablo

**Comment by jlelse** [comment]
I think I have the same problem #66

**Comment by ncapdevi** [comment]
Nope, we can't do a popBackStack because we have N number of backstacks, that's why this library was created. That being said, nothing that is happening in this library is any different than the Android system life cycle for Fragments https://developer.android.com/guide/components/fragments.html#Lifecycle  the question you're asking has to do with fragments, not the library, try searching on stackoverflow for any questions.
